"""init database

Revision ID: 95a9597e255f
Revises: 
Create Date: 2026-03-12 16:20:14.310300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95a9597e255f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('ref_type', sa.Text(), nullable=True),
    sa.Column('ref_id', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('content_raw', sa.Text(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('version_id', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('representation_type', sa.String(length=32), server_default=sa.text("'original'"), nullable=False),
    sa.Column('parent_document_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("representation_type IN ('original', 'synthesized')", name='ck_documents_representation_type'),
    sa.CheckConstraint("status IN ('uploaded', 'pending', 'chunked', 'processing', 'indexed', 'ready', 'error')", name='ck_documents_status'),
    sa.ForeignKeyConstraint(['parent_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source', 'external_id', name='uq_documents_tenant_source_external')
    )
    op.create_index('idx_documents_parent_document_id', 'documents', ['parent_document_id'], unique=False)
    op.create_index('idx_documents_tenant_parent_repr', 'documents', ['tenant_id', 'parent_document_id', 'representation_type'], unique=False)
    op.create_index('idx_documents_tenant_source_external', 'documents', ['tenant_id', 'source', 'external_id'], unique=False)
    op.create_index('idx_documents_tenant_status', 'documents', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_documents_version_id'), 'documents', ['version_id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('limits_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('query_usages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=512), nullable=False),
    sa.Column('query_hash', sa.String(length=64), nullable=False),
    sa.Column('query_len', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('k_final', sa.Integer(), nullable=False),
    sa.Column('k_vector', sa.Integer(), nullable=True),
    sa.Column('k_bm25', sa.Integer(), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('tokens_query', sa.Integer(), nullable=False),
    sa.Column('tokens_context', sa.Integer(), nullable=False),
    sa.Column('tokens_total', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_query_usages_tenant_idempotency')
    )
    op.create_index(op.f('ix_query_usages_query_hash'), 'query_usages', ['query_hash'], unique=False)
    op.create_index(op.f('ix_query_usages_tenant_id'), 'query_usages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_query_usages_user_id'), 'query_usages', ['user_id'], unique=False)
    op.create_table('rate_limit_buckets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('window_sec', sa.Integer(), nullable=False),
    sa.Column('bucket_key', sa.Text(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('reset_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'scope', 'bucket_key', 'window_sec', name='uq_rate_limit_bucket')
    )
    op.create_index(op.f('ix_rate_limit_buckets_tenant_id'), 'rate_limit_buckets', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_rate_limit_buckets_user_id'), 'rate_limit_buckets', ['user_id'], unique=False)
    op.create_index('ix_rate_limit_scope_reset', 'rate_limit_buckets', ['tenant_id', 'user_id', 'scope', 'reset_at'], unique=False)
    op.create_table('tenant_settings',
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('plan_code', sa.Text(), server_default='free', nullable=False),
    sa.Column('quota_overrides_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enforce_user_rate_limit', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('max_users', sa.Integer(), server_default='10', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_quotas',
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.String(length=50), server_default='free', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('max_requests', sa.Integer(), server_default='10000', nullable=False),
    sa.Column('used_requests', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_tokens', sa.Integer(), server_default='10000000', nullable=False),
    sa.Column('used_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_storage_mb', sa.Integer(), server_default='1024', nullable=False),
    sa.Column('used_storage_mb', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), server_default='user', nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('secret_hash', sa.String(length=255), nullable=False),
    sa.Column('prefix', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prefix')
    )
    op.create_table('user_quotas',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('plan', sa.String(length=50), server_default='free', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('max_tokens', sa.Integer(), server_default='1000000', nullable=False),
    sa.Column('used_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_requests', sa.Integer(), server_default='1000', nullable=False),
    sa.Column('used_requests', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_storage_mb', sa.Integer(), server_default='100', nullable=False),
    sa.Column('used_storage_mb', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('usage_ledger',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('api_key_id', sa.BigInteger(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('tokens_input', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tokens_output', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tokens_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('request_cost', sa.Numeric(precision=10, scale=6), server_default='0', nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'request_id', name='uq_usage_tenant_request')
    )
    op.create_index(op.f('ix_usage_ledger_request_id'), 'usage_ledger', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_ledger_request_id'), table_name='usage_ledger')
    op.drop_table('usage_ledger')
    op.drop_table('user_quotas')
    op.drop_table('api_keys')
    op.drop_table('users')
    op.drop_table('tenant_quotas')
    op.drop_table('tenants')
    op.drop_table('tenant_settings')
    op.drop_index('ix_rate_limit_scope_reset', table_name='rate_limit_buckets')
    op.drop_index(op.f('ix_rate_limit_buckets_user_id'), table_name='rate_limit_buckets')
    op.drop_index(op.f('ix_rate_limit_buckets_tenant_id'), table_name='rate_limit_buckets')
    op.drop_table('rate_limit_buckets')
    op.drop_index(op.f('ix_query_usages_user_id'), table_name='query_usages')
    op.drop_index(op.f('ix_query_usages_tenant_id'), table_name='query_usages')
    op.drop_index(op.f('ix_query_usages_query_hash'), table_name='query_usages')
    op.drop_table('query_usages')
    op.drop_table('plans')
    op.drop_index(op.f('ix_documents_version_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index('idx_documents_tenant_status', table_name='documents')
    op.drop_index('idx_documents_tenant_source_external', table_name='documents')
    op.drop_index('idx_documents_tenant_parent_repr', table_name='documents')
    op.drop_index('idx_documents_parent_document_id', table_name='documents')
    op.drop_table('documents')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
